export type ArchitectureModule = {
  key: string;
  title: string;
  group: string;
  href: string;
  level: "dedicated" | "universal";
  description: string;
  features: string[];
};

const dedicated = (href: string) => ({ href, level: "dedicated" as const });
const universal = (key: string) => ({ href: `/erp/${key}`, level: "universal" as const });

export const architectureModules: ArchitectureModule[] = [
  { key: "dashboard", title: "CEO Command Center", group: "Command", ...dedicated("/dashboard"), description: "Owner cockpit for revenue, cash, fleet, alerts, compliance, profit, and charts.", features: ["Daily cash flow", "Revenue and profit", "Fleet utilization", "Compliance alerts", "AI alerts"] },
  { key: "fleet-management", title: "Fleet Management", group: "Fleet", ...dedicated("/vehicles"), description: "Vehicle master, ownership, devices, documents, technical details, and attachments.", features: ["RC", "Insurance", "Permit", "GPS IMEI", "Dashcam IMEI", "Odometer", "Loan details"] },
  { key: "driver-management", title: "Driver Management", group: "Fleet", ...dedicated("/drivers"), description: "Driver profile, KYC, license, salary, performance, AI score, violations, and training.", features: ["License", "Aadhaar", "PAN", "Bank", "Attendance", "Violations", "Training"] },
  { key: "customer-crm", title: "Customer CRM", group: "CRM", ...dedicated("/customers"), description: "Customer master, contracts, credit, trips, invoices, payments, and tickets.", features: ["GST", "PAN", "Credit limit", "Rate contracts", "Support tickets"] },
  { key: "trip-management", title: "Trip Management", group: "TMS", ...dedicated("/trips"), description: "Enquiry-to-payment trip lifecycle with dispatch, POD, invoice, and profit.", features: ["Quotation", "Assignment", "POD", "Invoice", "Payment", "Margin"] },
  { key: "trip-settlement", title: "Trip Settlement", group: "Settlement ERP", ...universal("trip-settlement"), description: "Settle every trip with advance, diesel, toll, loading, unloading, detention, POD, invoice, receipt, and driver balance in one place.", features: ["Trip sheet", "Driver advance", "Recoverables", "Invoice payment", "Trip P&L", "Settlement voucher"] },
  { key: "stationery-management", title: "Stationery Management", group: "Settlement ERP", ...universal("stationery-management"), description: "Track waybills, receipt books, invoice books, gate passes, seals, POD forms, branch stock, and issue history.", features: ["Waybills", "Receipt books", "POD forms", "Branch issue", "Serial control", "Audit trail"] },
  { key: "owned-vehicle-operations", title: "Owned Vehicle Operations", group: "Operations ERP", ...universal("owned-vehicle-operations"), description: "Run owned-fleet jobs from consignment booking to challan, loading, dispatch, arrival, E-POD, billing, and vehicle profitability.", features: ["Booking", "Load plan", "Dispatch", "Arrival", "E-POD", "Vehicle profit"] },
  { key: "consignment-ptl-ftl", title: "PTL / FTL Consignment", group: "Operations ERP", ...universal("consignment-ptl-ftl"), description: "Manage partial-load and full-load consignments with capacity planning, e-way references, customer terms, and fulfillment status.", features: ["PTL", "FTL", "Capacity", "E-way bill", "Load status", "Customer SLA"] },
  { key: "challan-epod", title: "Challan, Arrival & E-POD", group: "Operations ERP", ...universal("challan-epod"), description: "Create challans, map them to trips/jobs, record arrival, upload POD, close shortages/damages, and release billing.", features: ["Challan", "Job mapping", "Arrival", "E-POD", "Shortage", "Billing release"] },
  { key: "finance-revenue-operations", title: "Operations Finance & Revenue", group: "Finance ERP", ...universal("finance-revenue-operations"), description: "Control advances, freight bills, supplementary bills, receipts, deductions, detention, and revenue leakage across every job.", features: ["Consignment advance", "Freight bill", "Supplementary bill", "Receipt", "Deduction", "Leakage control"] },
  { key: "client-rate-chart", title: "Client Rate Chart", group: "Finance ERP", ...universal("client-rate-chart"), description: "Maintain customer lane rates, vehicle-type pricing, fuel surcharge, detention terms, loading charges, expiry dates, and approval history.", features: ["Lane rate", "Vehicle type", "Detention", "Fuel surcharge", "Expiry", "Approval"] },
  { key: "hired-vehicle-operations", title: "Hired Vehicle Operations", group: "Operations ERP", ...universal("hired-vehicle-operations"), description: "Manage market and attached vehicles with hire slips, owner advances, detention, E-POD, payable settlement, and broker commission.", features: ["Hire slip", "Owner advance", "Detention", "Market E-POD", "Payable", "Brokerage"] },
  { key: "account-management-erp", title: "Account Management ERP", group: "Accounts ERP", ...universal("account-management-erp"), description: "Structure account groups, ledgers, manual vouchers, auto vouchers, receipt/payment entries, and audit-ready ledger transactions.", features: ["Account groups", "Ledgers", "Manual vouchers", "Auto vouchers", "Cash book", "Bank book"] },
  { key: "maintenance-erp", title: "Maintenance ERP", group: "Maintenance ERP", ...universal("maintenance-erp"), description: "Plan service history, work orders, parts inventory, tyre lifecycle, battery health, vendor bills, downtime, and vehicle release.", features: ["Service history", "Work order", "Parts", "Tyres", "Battery", "Downtime"] },
  { key: "cost-of-ownership", title: "Cost of Ownership", group: "Owner Analytics", ...universal("cost-of-ownership"), description: "See true vehicle cost across EMI, insurance, permits, fuel, tyre, maintenance, driver, toll, FASTag, downtime, and trip revenue.", features: ["Vehicle P&L", "Fixed cost", "Variable cost", "Cost per KM", "Downtime", "ROI"] },
  { key: "dispatch-planning", title: "Dispatch Planning", group: "TMS", ...dedicated("/tms"), description: "Load, vehicle, driver, trailer availability and conflict detection.", features: ["Calendar", "Availability", "Auto assignment", "Conflict detection"] },
  { key: "gps-tracking", title: "GPS Tracking", group: "Tracking", ...dedicated("/fleet-map"), description: "Live map, playback, stops, geofence, mileage, route replay, and ETA.", features: ["Live map", "Playback", "Geofence", "Idle", "Overspeed", "ETA"] },
  { key: "ai-camera", title: "AI Camera Integration", group: "AI Safety", ...dedicated("/live-dashcam"), description: "Live cameras, playback, DMS, ADAS, event clips, and cloud evidence.", features: ["Fatigue", "Phone usage", "Seat belt", "Collision warning", "Lane departure"] },
  { key: "fuel-management", title: "Fuel Management", group: "Finance", ...dedicated("/fuel-management"), description: "Fuel entries, mileage, fuel card, vendor, theft/refill, and expected-vs-actual.", features: ["Fuel card", "Mileage", "Fuel theft", "Fuel vendor", "Diesel inventory"] },
  { key: "fastag-management", title: "FASTag Management", group: "Finance", ...universal("fastag-management"), description: "FASTag recharge, balance, transactions, wrong deductions, and trip-wise toll cost.", features: ["Recharge", "Balance", "Transactions", "Wrong deduction", "Vehicle-wise toll"] },
  { key: "tyre-management", title: "Tyre Management", group: "Workshop", ...dedicated("/tyre-management"), description: "Tyre inventory, rotation, retreading, serial tracking, warranty, and cost per KM.", features: ["Inventory", "Rotation", "Retreading", "Warranty", "Cost per KM"] },
  { key: "workshop-module", title: "Workshop Module", group: "Workshop", ...dedicated("/maintenance-center"), description: "Job cards, mechanic, labour, parts, AMC, repair cost, and downtime.", features: ["Preventive", "Corrective", "Breakdown", "Job card", "Downtime"] },
  { key: "spare-parts", title: "Spare Parts", group: "Inventory", ...universal("spare-parts"), description: "Parts inventory, purchase, consumption, transfer, warranty, barcode, and QR.", features: ["Inventory", "Purchase", "Consumption", "Transfer", "Minimum stock"] },
  { key: "preventive-maintenance", title: "Preventive Maintenance", group: "Workshop", ...dedicated("/maintenance-alerts"), description: "Service schedules by KM, hours, days, trips, and automatic reminders.", features: ["KM", "Engine hours", "Oil", "Filters", "Battery", "Reminders"] },
  { key: "breakdown-management", title: "Breakdown Management", group: "Workshop", ...universal("breakdown-management"), description: "SOS, location, photos, vendor, mechanic, tow truck, ETA, and live status.", features: ["SOS", "Location", "Tow truck", "Estimated cost", "Live status"] },
  { key: "finance-module", title: "Finance Module", group: "Finance", ...dedicated("/payments"), description: "Income, expense, bank, cash book, ledger, GST, TDS, P&L, and balance sheet.", features: ["Cash book", "Bank", "GST", "TDS", "Ledger", "P&L"] },
  { key: "billing", title: "Billing", group: "Finance", ...dedicated("/billing-packs"), description: "Auto invoices, GST, e-invoice, e-way bill, trip billing, and statements.", features: ["Auto invoice", "GST", "E-way bill", "Customer statement"] },
  { key: "accounts-receivable", title: "Accounts Receivable", group: "Finance", ...dedicated("/receivables"), description: "Outstanding, ageing, reminders, collection, recovery, and customer ledger.", features: ["Ageing", "Reminder", "Interest", "Recovery", "Customer ledger"] },
  { key: "accounts-payable", title: "Accounts Payable", group: "Finance", ...universal("accounts-payable"), description: "Vendor bills, diesel/workshop/tyre vendors, brokers, payments, and ageing.", features: ["Vendor bills", "Payments", "Ageing", "Broker payable"] },
  { key: "hr-module", title: "HR Module", group: "HR", ...universal("hr-module"), description: "Attendance, leave, payroll, ESIC, PF, bonus, advances, loans, and ID cards.", features: ["Attendance", "Leave", "Payroll", "ESIC", "PF", "Overtime"] },
  { key: "compliance", title: "Compliance", group: "Compliance", ...dedicated("/document-center"), description: "Insurance, permits, FC, PUC, road tax, licenses, medical, AIS140, and renewals.", features: ["Insurance", "Permit", "Fitness", "PUC", "AIS140", "Renewals"] },
  { key: "document-management", title: "Document Management", group: "Compliance", ...dedicated("/document-center"), description: "Scan, upload, version, expiry, search, share, download, and OCR search.", features: ["Upload", "Version", "Expiry", "Share", "OCR search"] },
  { key: "vendor-management", title: "Vendor Management", group: "Procurement", ...universal("vendor-management"), description: "Fuel, workshop, tyre, insurance, finance, GPS, camera, repair, and ratings.", features: ["Vendor ratings", "Repair", "Insurance", "GPS", "Camera"] },
  { key: "inventory", title: "Inventory", group: "Inventory", ...universal("inventory"), description: "Consumables, lubricants, uniforms, tools, safety items, and stock alerts.", features: ["Oil", "Grease", "Coolant", "Uniform", "Tools"] },
  { key: "purchase-module", title: "Purchase Module", group: "Procurement", ...universal("purchase-module"), description: "Purchase request, approval, PO, GRN, vendor bills, and inventory update.", features: ["PR", "Approval", "PO", "GRN", "Vendor bills"] },
  { key: "sales-module", title: "Sales Module", group: "Sales", ...universal("sales-module"), description: "Quotation, rate contract, follow-up, CRM pipeline, won/lost.", features: ["Quotation", "Rate contract", "Pipeline", "Won", "Lost"] },
  { key: "fleet-brokerage", title: "Fleet Brokerage", group: "Brokerage", ...universal("fleet-brokerage"), description: "Own, attached, market, broker vehicles, commission, ledgers, and settlements.", features: ["Attached vehicles", "Commission", "Load board", "Broker ledger"] },
  { key: "load-marketplace", title: "Load Marketplace", group: "Brokerage", ...universal("load-marketplace"), description: "Available loads, vehicles, matching engine, nearby vehicles, bids, and auction.", features: ["Loads", "Vehicles", "Matching", "Bids", "Auction"] },
  { key: "mining-erp", title: "Mining ERP", group: "Verticals", ...universal("mining-erp"), description: "Trip token, royalty, weighbridge, mining pass, loading point, shift, and production.", features: ["Royalty", "Weighbridge", "Mining pass", "Crusher", "Production"] },
  { key: "construction-erp", title: "Construction ERP", group: "Verticals", ...universal("construction-erp"), description: "Machines, operators, diesel, usage hours, project cost, clients, and sites.", features: ["Excavator", "JCB", "Hywa", "Crane", "Usage hours"] },
  { key: "reefer-management", title: "Reefer Management", group: "Verticals", ...universal("reefer-management"), description: "Temperature, humidity, door open, cooling unit alerts, graphs, and compliance.", features: ["Temperature", "Humidity", "Door open", "Pharma", "Food compliance"] },
  { key: "tanker-management", title: "Tanker Management", group: "Verticals", ...universal("tanker-management"), description: "Compartments, seals, cleaning certificate, hazmat, pressure, and liquid level.", features: ["Compartments", "Seal numbers", "Hazmat", "Pressure"] },
  { key: "school-bus", title: "School Bus", group: "Verticals", ...universal("school-bus"), description: "Students, routes, parents, attendance, pickup, drop, live tracking, notifications.", features: ["Students", "Parents", "Pickup", "Drop", "Attendance"] },
  { key: "employee-transport", title: "Employee Transport", group: "Verticals", ...universal("employee-transport"), description: "Roster, shifts, pickup/drop, attendance, tracking, and billing.", features: ["Roster", "Shift", "Attendance", "Billing"] },
  { key: "ai-analytics", title: "AI Analytics", group: "Analytics", ...dedicated("/risk-engine"), description: "Vehicle, driver, fleet score, profit, breakdown, fuel, maintenance, and demand prediction.", features: ["Vehicle score", "Driver score", "Breakdown prediction", "Demand forecast"] },
  { key: "business-intelligence", title: "Business Intelligence", group: "Analytics", ...dedicated("/reports"), description: "Dashboards, custom reports, pivots, scheduled reports, Excel/PDF/email exports.", features: ["Custom reports", "Pivot", "Excel", "PDF", "Email"] },
  { key: "mobile-apps", title: "Mobile Apps", group: "Apps", ...dedicated("/driver-app"), description: "Driver, owner, mechanic, dispatcher, customer, and broker app workflows.", features: ["Driver app", "Owner app", "Mechanic app", "Customer app"] },
  { key: "notifications", title: "Notifications", group: "Automation", ...universal("notifications"), description: "SMS, WhatsApp, email, push, voice call, and in-app notifications.", features: ["SMS", "WhatsApp", "Email", "Push", "Voice"] },
  { key: "security", title: "Security", group: "Admin", ...universal("security"), description: "RBAC, 2FA, audit logs, IP/device restrictions, and encryption.", features: ["Roles", "2FA", "Audit", "IP restriction"] },
  { key: "integrations", title: "Integrations", group: "Admin", ...universal("integrations"), description: "GPS, dashcams, FASTag, fuel cards, banks, Tally, GST, e-way bill, WhatsApp, IoT.", features: ["GPS", "Dashcams", "FASTag", "Tally", "GST", "WhatsApp"] },
  { key: "workflow-approvals", title: "Workflow & Approvals", group: "Automation", ...universal("workflow-approvals"), description: "Approval chains, signatures, mobile approval, escalation, reminders, and history.", features: ["Trip approval", "Fuel request", "Vendor payment", "Approval history"] },
  { key: "route-optimization", title: "Route & Logistics Optimization", group: "TMS", ...dedicated("/route-planner"), description: "Route optimization, multi-stop, consolidation, backhaul, toll/fuel optimization, ETA.", features: ["Multi-stop", "Backhaul", "Deadhead reduction", "ETA prediction"] },
  { key: "asset-management", title: "Asset Management", group: "Assets", ...universal("asset-management"), description: "GPS, dashcams, SIMs, fuel cards, FASTag, phones, tools, safety equipment, and warranty.", features: ["GPS devices", "Dashcams", "SIM cards", "Fuel cards", "Warranty"] },
  { key: "contracts-rate-management", title: "Contracts & Rate Management", group: "Sales", ...universal("contracts-rate-management"), description: "Customer contracts, lane rates, detention, fuel surcharge, seasonal pricing, and expiry alerts.", features: ["Lane rates", "Detention", "Fuel surcharge", "Expiry alerts"] },
  { key: "claims-incidents", title: "Claims & Incident Management", group: "Compliance", ...universal("claims-incidents"), description: "Accident, insurance, cargo damage, theft, evidence, FIR, repair estimates, and settlements.", features: ["Accident", "Cargo damage", "FIR", "Evidence", "Settlement"] },
  { key: "customer-self-service", title: "Customer Self-Service Portal", group: "CRM", ...dedicated("/customer-portal"), description: "Booking, tracking, invoices, PODs, history, support tickets, event clips, payments.", features: ["Book", "Track", "Download POD", "Pay online"] },
  { key: "business-rules", title: "Business Rules Engine", group: "Automation", ...universal("business-rules"), description: "No-code rules for assignment, dispatch blocks, approvals, alerts, and automations.", features: ["Auto assign", "Block dispatch", "Expense limits", "Triggers"] },
  { key: "master-data", title: "Master Data Management", group: "Admin", ...universal("master-data"), description: "Branches, depots, customers, vendors, drivers, vehicles, and reference masters.", features: ["Branches", "Depots", "Customers", "Vendors", "Drivers"] },
];

export function findArchitectureModule(key: string) {
  return architectureModules.find((item) => item.key === key);
}
